names:
- Artilary
- Missile
- Radar
- M. Rocket Launcher
- Soldier
- Tank
- Vehicle
nc: 7
test: archive/KIIT-MiTA/test/images
train: archive/KIIT-MiTA/train/images
val: archive/KIIT-MiTA/valid/images
